excluded:
  - Pods
  - .git
  - R.*

disabled_rules:
  - class_delegate_protocol
  - weak_delegate
  - todo
  - cyclomatic_complexity
  - function_body_length
  - generic_type_name
  - identifier_name
  - trailing_whitespace

opt_in_rules:
  - unused_closure_parameter
  - unused_capture_list
  - overridden_super_call
  - prohibited_super_call
  - explicit_init
  - operator_usage_whitespace

large_tuple: 4

line_length:
  warning: 180

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500

type_body_length:
  warning: 400
  error: 450

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

identifier_name:
  min_length: 1
  max_length: 65

type_name:
  min_length: 3
  max_length: 65

included:
  - junction-2021

mark:
  severity: error

reporter: xcode # reporter type (xcode, json, csv, checkstyle, junit, emoji)
